[package]
name = "rewards"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "RAÍZ · Contrato Rewards — puntos y premios"

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
